### ISSUE TITLE
DatePicker Input field is accepting invalid values like float, negative, special characters.

### ISSUE THREAD

**Issue by kalyanixraut** [IBM/carbon-components-react#967] opened 2018-06-05 05:40 UTC
## Detailed description
I have used DatePicker - single with calendar component in the dashboard and have found that invalid characters like float/nagative numbers or special characters can be entered in the date picker input box and in year box.

Expected behavior is date picker input  box shouldn't allow user to type-in any invalid characters and prompt a message to input correct date format.

We are using this version of carbon :
"carbon-components": "8.18.0", "carbon-components-react": "5.34.0",

## Steps to reproduce the issue
The issue can easily be replicated in the react component storybook itself.
1. Open the react carbon design system story book url. and select Date Picker single with calendar.
[storybook](http://react.carbondesignsystem.com/?selectedKind=DatePicker&selectedStory=single%20with%20calendar&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

2. Type in float/negative/special characters in the input field.
3. Try typing invalid characters in the calendar year field.

![carbondateissue](https://user-images.githubusercontent.com/22093326/40956973-576420a4-6882-11e8-9791-05c7cdaa6fc4.jpg)

**Comment by asudoh** [comment] 2018-06-05 07:18
Hi @kalyanixraut thank you for reporting! There are a few props in `<DatePickerInput>` that you may want to try:

1. `onChange` (callback) - You can capture what user types with it
2. `invalid` (boolean) - If you set `true`, our form validation UI will be shown
3. `invalidText` (string) - The text shown in our form validation UI

**Comment by tw15egan** [comment] 2018-06-27 19:48
@kalyanixraut, were these props able to solve your issue?

**Comment by joshblack** [comment] 2018-07-30 16:45
Going to close this due to in-activity. Feel free to re-open if you can provide some steps to reproduce!

**Closed by joshblack** 2018-07-30 16:45 UTC
