### ISSUE TITLE
[OverflowMenu] position is incorrect after window resize

### ISSUE THREAD

**Issue by joker23** [IBM/carbon-components-react#867] opened 2018-05-07 21:11 UTC
Position of the overflow menu is incorrect after resize

## Detailed description

When resizing the window, the OverflowMenu component does not update its position. So the element
that the overflow menu is attached to might have moved to accommodate the new size, but the menu will stay where it was initially. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

OverflowMenu

> What did you expect to happen? What happened instead? What would you like to see changed?

Overflow menu will be positioned correctly

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

5.41.6

## Steps to reproduce the issue

1. Open the overflow menu
2. resize the window

## Additional information

* Screenshots or code
* Notes

**Comment by asudoh** [comment] 2018-05-08 03:00
Hi @joker23 thank you for reporting! Do you have a reproducible case, like one based on https://codesandbox.io/s/x2mjypo6pp? Thanks!

**Comment by joshblack** [comment] 2018-07-30 16:40
Closing this due to in-activity. Feel free to re-open!

**Closed by joshblack** 2018-07-30 16:40 UTC
