### ISSUE TITLE
OverflowMenu closes when an item is selected

### ISSUE THREAD

**Issue by huydoan2** [IBM/carbon-components-react#1805] opened 2019-01-29 22:20 UTC
## Detailed description

**Describe in detail the issue you're having.**
I'm using the OverflowMenu to host several CheckBoxes. I expect the menu not to close when I select the items. However, the menu automatically closes when I click on any item.

The previous behavior is that the menu only closes when I click outside of the menu and that makes sense. Upgrading to version 6.83.1 results in this issue. The previous version that it works is 6.71.0.

**Is this issue related to a specific component?**
The OverflowMenu component.

**What browser are you working in?**
Chrome 71.0 and and Firefox Developer Edition 65.0 b11.

**What version of the Carbon Design System are you using?**
6.83.1

**What offering/product do you work on? Any pressing ship or release dates we should be aware of?**
Bluemix/Bluemix.UnifiedSupport.
This issue affects daily user experience in production.

## Steps to reproduce the issue

1. Step one
Go to the OverflowMenu component in the storybook

2. Step two
Choose any kind of OverflowMenu and pop the menu open

3. Step three
Click on any option and see the menu automatically closes

**Comment by huydoan2** [comment] 2019-02-05 18:47
@emyarod It was not the behavior in version 6.71.0. The menu only closes when the user clicks outside of the menu.

To your clarification, it's similar to that but not quite. I don't necessarily need the manual control of the menu closing moment. It is just the behavior or closing the menu when clicking outside is more intuitive and fits the needs of the support center application since we have checkboxes in the OverflowMenu.

You could see the current Support Center at `dev.console.test.cloud.ibm.com/unifiedsupport/manage` and click on the filter icon on the TableToolbar.

**Comment by huydoan2** [comment] 2019-02-06 18:10
@asudoh you got me.

**Comment by xzy202** [comment] 2019-02-18 20:31
Hi , we had the same issue where we have several checkboxes in the overflow menu. When you click the checkbox, the overflow menu is closed. So we are not able to do select/unselect at all. 
![screen shot 2019-02-18 at 12 14 37 pm](https://user-images.githubusercontent.com/25212562/52975014-8f9c7b80-3378-11e9-9563-0b9866082f34.png)
Previously , we used  "carbon-components": "9.29.2", "carbon-components-react": "6.40.1".  

After upgrading to "carbon component" to 9.66.3 and  "carbon-components-react": "6.74.0" , we met this problem.

**Comment by emyarod** [comment] 2019-02-20 17:37
@huydoan2 @xzy202 so I went back and built several previous versions of `carbon-components-react` including the versions you mentioned, but was unable to replicate the expected behavior in the respective storybook builds for each version. Would it be possible for one or both of you to create a [reduced test case](https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox) that showcases the expected behavior? I first want to make sure if this was a regression or possibly unintended behavior in a previous version. But an alternative I have been considering as I mentioned earlier in this thread was adding the ability to manually control the open/closed state of the overflow menu

**Comment by asudoh** [comment] 2019-02-21 05:10
Stopping propagation of `onClick` event on the containing element makes the check box work, like:

```javascript
<OverflowMenuItem
  {...overflowMenuItemProps}
  itemText={
    <div onClick={evt => { evt.stopPropagation(); }}>
      <Checkbox id="my-checkbox" labelText="Checkbox" />
    </div>
  }
/>
```

My investigation also showed that `6.71.0` and our latest release works in a similar way, and thus we need more info (e.g. a reduced case based on https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox as @emyarod pointed out). Thanks!

**Comment by asudoh** [comment] 2019-02-21 06:36
BTW I saw a regression that caused #1885, and wondering if it's same as this issue. To see that, would you try making a change to `node_modules/carbon-components-react/es/components/OverflowMenu/OverflowMenu.js` and `node_modules/carbon-components-react/lib/components/OverflowMenu/OverflowMenu.js` like below? Thanks!

```diff
--- carbon-components-react/es/components/OverflowMenu/OverflowMenu.js.orig     2019-02-21 15:32:39.760643700 +0900
+++ carbon-components-react/es/components/OverflowMenu/OverflowMenu.js  2019-02-21 15:32:10.545972700 +0900
@@ -220,11 +220,13 @@
     });

     _defineProperty(_assertThisInitialized(_assertThisInitialized(_this)), "handleClick", function (evt) {
+      if (!_this._menuBody || !_this._menuBody.contains(evt.target)) {
       _this.setState({
         open: !_this.state.open
       });

       _this.props.onClick(evt);
+      }
     });

     _defineProperty(_assertThisInitialized(_assertThisInitialized(_this)), "handleKeyDown", function (evt) {
```

**Comment by asudoh** [comment] 2019-02-23 02:17
Closing as a duplicate of #1885 - Feel free to let us know if anybody believes otherwise - Thanks!

**Closed by asudoh** 2019-02-23 02:17 UTC
Labels: project: components, status: needs more info 🤷‍♀️, type: dev :robot:, type: enhancement 💡
