### ISSUE TITLE
MultiSelect : initialSelectedItems is showing issues

### ISSUE THREAD

**Issue by prakashchandrabarnwal** [IBM/carbon-components-react#511] opened 2018-01-19 07:40 UTC
## Detailed description
 When we tried to use initialSelectedItems MultiSelect is not working as expected. what should be the structure of collection with pre-selected values.
 
 items : const minuteData=Array(3).fill().map((e, i) => {return { text:(i+1).toString(), value:i+1 }});

  const initialSelectedItems=items
 //const initialSelectedItems=[{text:"1"}]
 //const initialSelectedItems=[{value:1}]
 //const initialSelectedItems=[1]
 //const initialSelectedItems=["1"]
 //const initialSelectedItems=[{text:"1",value:1}]

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?
MultiSelect

> Is this issue related to a specific component?
  MultiSelect

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?
 Chrome

> What version of the Carbon Design System are you using?
    "carbon-components": "^8.6.0",
    "carbon-components-react": "^5.9.1",
    "carbon-icons": "^6.2.0"

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
```
import React, { Component } from 'react';
import MultiSelect from 'carbon-components-react/lib/components/MultiSelect';
import 'carbon-components/scss/globals/scss/styles.scss';

const minuteData=Array(3).fill().map((e, i) => {return { text:(i+1).toString(), value:i+1 }});

//const preSelectedValues=minuteData
//const preSelectedValues=[{text:"1"}]
//const preSelectedValues=[{value:1}]
//const preSelectedValues=["1"]
const preSelectedValues=[{text:"1",value:1}]


class App extends Component {
    state = {
        selectedItems: [],
    }

    handleChange = changes => {
        this.setState({ selectedItems: changes.selectedItems });
        console.log(this.state.selectedItems.map((data)=>{return data.value}).toString())
    }

    render() {
        return (
            <div>
                <MultiSelect
                    className='hour-setMinute'
                    label="Minute"
                    initialSelectedItems={preSelectedValues}
                    items={minuteData}
                    itemToString={item=>(item ? item.text : '')}
                    onChange={(value) => { this.handleChange(value) }}
                />

            </div>
        );
    }
}


export default App;
```

if we provide preSelectedValues=items

checkbox is not responding

![case-1](https://user-images.githubusercontent.com/20160628/35139402-efff7dde-fd18-11e7-850d-75d87a18c6a0.gif)

if we provide preSelectedValues=[{text:"1",value:1}]

checkbox is not checked with provided initial value
![case-2](https://user-images.githubusercontent.com/20160628/35139569-bc08624c-fd19-11e7-87ff-ec02a44cd5dd.gif)

* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by joshblack** [comment] 2018-01-19 19:20
Hi there @prakashchandrabarnwal! The issue here is that `initialSelectedItems` expects an array of items that exist in `items`. More specifically, it expects the references to be the same.

For example:

```js
const items = [
  {
    id: 'option-1',
    text: 'Option 1',
  },
  {
    id: 'option-2',
    text: 'Option 2',
  },
  {
    id: 'option-3',
    text: 'Option 3',
  },
  {
    id: 'option-4',
    text: 'Option 4',
  },
];

<MultiSelect
  label="Label"
  items={items}
  itemToString={item => (item ? item.text : '')}
  initialSelectedItems={[items[0], items[1]]}
  onChange={action('onChange - Inline MultiSelect')}
/>

```

**Comment by prakashchandrabarnwal** [comment] 2018-01-19 21:40
@joshblack If  we populate initialSelectedItems as an array of items that exist in items and if it references to be the same.

e.g. 
```
const items = [
    {
        id: 'option-1',
        text: 'Option 1',
    },
    {
        id: 'option-2',
        text: 'Option 2',
    },
    {
        id: 'option-3',
        text: 'Option 3',
    },
    {
        id: 'option-4',
        text: 'Option 4',
    },
];
```
```
const prevValue=[items[0], items[1]]

```

```

  <MultiSelect
                    label="Label"
                    items={items}
                    itemToString={item => (item ? item.text : '')}
                    initialSelectedItems={prevValue}
                    onChange={(value)=>{this.handleChange(value)}}
                />

```

Pre-Selected checkboxes are not clickable

````
import React, { Component } from 'react';
import MultiSelect from '../node_modules/carbon-components-react/lib/components/MultiSelect';
import 'carbon-components/scss/globals/scss/styles.scss';

const items = [
    {
        id: 'option-1',
        text: 'Option 1',
    },
    {
        id: 'option-2',
        text: 'Option 2',
    },
    {
        id: 'option-3',
        text: 'Option 3',
    },
    {
        id: 'option-4',
        text: 'Option 4',
    },
];

const prevValue=[items[0], items[1]]

class App extends Component {
    state = {
        selectedItems: [],
    }

    handleChange = changes => {
        this.setState({ selectedItems: changes.selectedItems });
        console.log(this.state.selectedItems.map((data)=>{return data.text}).toString())
    }

    render() {
        return (
            <div>
                <MultiSelect
                    label="Label"
                    items={items}
                    itemToString={item => (item ? item.text : '')}
                    initialSelectedItems={prevValue}
                    onChange={(value)=>{this.handleChange(value)}}
                />

            </div>
        );
    }
}

**Comment by joshblack** [comment] 2018-05-18 15:31
Hmm, having a hard time reproducing this. Updated the story to follow the same scheme that you provided, e.g.:

```jsx
  .addWithInfo(
    'with initial selected items',
    `
      Provide a set of items to initially select in the control
    `,
    () => {
      const prevItems = [items[0], items[1]];
      return (
        <div style={{ width: 300 }}>
          <MultiSelect
            label={defaultLabel}
            items={items}
            itemToString={item => (item ? item.text : '')}
            initialSelectedItems={prevItems}
            onChange={action('onChange - Inline MultiSelect')}
          />
        </div>
      );
    }
  )
```

And the component was behaving as expected. Going to close this for now, feel free to re-open if the issue still exists! Including a codesandbox link from the issue template that demonstrates the issue would also help out a ton with debugging here!

**Comment by matuagarwal** [comment] 2018-08-07 10:53
@joshblack We dont have access to re-open this issue, can you please reopen it on our behalf since we are still facing this problem ?

Here is the sandbox where the problem is recreated
https://codesandbox.io/s/j37zqr01lw.

**Comment by elainamickelburgh** [comment] 2018-08-07 16:12
@joshblack do you have a feel for when this issue can be resolved please? Any help you can provide here would be much appreciated. One of our top customers are unable to solve a critical use case they have with our product as a result of this issue. They desperately need this before they push their workload from their dev environment to prod in just a few weeks. Please let me know if you need anything else from us. FYI @matuagarwal

**Comment by joshblack** [comment] 2018-08-08 15:37
Hi @elainamickelburgh! This issue isn't tasked for our current sprint, but feel free to contribute the fix for this and we'll make sure to merge it in and publish it!

**Comment by elainamickelburgh** [comment] 2018-08-10 13:53
Hi @joshblack we are unable to contribute the fix as we don't have the carbon skills to do so. Is it possible to make this your next sprint? How else can we get this piece of work prioritized?

**Comment by joshblack** [comment] 2018-08-10 14:36
The primary issue for this is that the items supplied are completely separate items each time. The reference for the items should be the same, for example:

https://codesandbox.io/s/n360v3pjnp

**Comment by elainamickelburgh** [comment] 2018-08-14 13:15
Ok @joshblack , I can see how this can be a problem. But my question still stands... how is the backlog prioritized? Are you able to share some information on that please? Or share an OM contact?

**Comment by elainamickelburgh** [comment] 2018-08-14 16:25
Hi @joshblack - thank you for your response. I'll have to let @matuagarwal or @tmruthyu explain in more detail the issue we are facing. Can you comment/share more details please @matuagarwal or @tmruthyu ?
Thanks for sharing your prioritization process, it's very helpful. I'll let our engineering team answer and then go from there.

**Comment by matuagarwal** [comment] 2018-08-17 11:01
Thanks @joshblack for your suggestion, its indeed working fine after putting the same reference, so closing this issue. We may reach out to you in case any more questions.
You can close this issue

**Closed** 2018-08-17 14:35 UTC
Labels: bug
