### ISSUE TITLE
[Accordion] broken dropdown inside

### ISSUE THREAD

**Issue by shixiedesign** [IBM/carbon-components-react#2037] opened 2019-03-18 19:22 UTC
Dropdown inside the accordion is broken. Chevron should be inside the field for options.

![image](https://user-images.githubusercontent.com/15144993/54557541-66780680-4989-11e9-80aa-57b99335933b.png)

Observed here (on Chrome): https://deploy-preview-2031--carbon-components-react.netlify.com/experimental/?selectedKind=Accordion

**Comment by emyarod** [comment] 2019-03-18 21:00
this should be resolved by #2031 (currently blocked), but you can confirm the issue is not present in the deploy preview for that branch

**Closed** 2019-03-19 21:56 UTC
Labels: project: components, type: bug 🐛
