### ISSUE TITLE
Could the AccordionItem heading be a div instead of a button?

### ISSUE THREAD

**Issue by kevinkbender** [IBM/carbon-components-react#1179] opened 2018-08-10 15:54 UTC
> Describe in detail the issue you're having.

The heading of the AccordionItem is a `<button>`.  I think in some browsers, when you click inside a button, it just counts as clicking on the button instead of clicking on the specific element.  I know it is like this in Firefox, but not Chrome - I am not sure about other browsers.

Could it be changed to a `<div>` so that we can click on specific items inside of the header?

See here: https://codesandbox.io/s/6j2njyj7pz

> Is this issue related to a specific component?

AccordionItem

> What browser are you working in?

Chrome/Firefox

**Comment by asudoh** [comment] 2018-08-10 21:06
Hi 👋 thank you for reporting! If I understand your concern correctly, clicking of an inner-element causes `click` event firing on the inner-element as well as the outer-element, regardless of `<div>` vs. `<button>` ([ref](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#Event_bubbling_and_capture)). That said, you may want to try `onSpanClick = evt => { evt.stopPropagation(); }` if it was your intent?

**Comment by kevinkbender** [comment] 2018-08-10 21:39
I think in Firefox, clicking a `<button>`'s inner element causes the `click` event to fire ONLY on the `<button>`.  The `onSpanClick` function is never called.

**Comment by asudoh** [comment] 2018-08-10 22:30
I see thank you for clarifying @kevinkbender! I see you need to hook the event on the `<button>` with Firefox. Given I believe `<button>` tag choice is for expressing the context of the expando - Are you interested in explaining your motivation to use `<div>` there?

**Comment by kevinkbender** [comment] 2018-08-13 14:41
We're trying to put some options with checkboxes inside the body of the AccordionItem.  We also want to put a checkbox in the heading of the AccordionItem, which you can use to check/uncheck all the checkboxes in the body.

**Comment by asudoh** [comment] 2018-08-13 22:42
@aagonzales @designertyler Do you think check box in accordion heading is something that makes sense as Carbon design? Thanks!

**Comment by joshblack** [comment] 2018-08-23 18:20
Going to close this as a duplicate of #1178. Feel free to move the conversation over there!

**Closed by joshblack** 2018-08-23 18:20 UTC
Labels: discussion
