### ISSUE TITLE
Console errors about ListBoxMenuIcon & ListBoxField proptypes

### ISSUE THREAD

**Issue by Yohanna** [IBM/carbon-components-react#1358] opened 2018-09-24 19:44 UTC
I'm getting React warnings about wrong proptypes whenever I use a Carbon component that uses `ListBox` or `ListBoxField` under the hood. 

_Failed prop type: Invalid prop `children` of type `ListBoxMenuIcon` supplied to `ListBoxField`, expected each child to be one of: `[ListBoxMenuIcon, ListBoxSelection, span, input]`_

The error itself doesn't make sense since `ListBoxMenuIcon` is already one of the expected proptypes!

Same thing for this:

_Failed prop type: Invalid prop `children` of type `ListBoxField` supplied to `ListBox`, expected each child to be one of: `[ListBoxField, ListBoxMenu]`_

I think I've narrowed down the root cause to the `react-hot-loader` library. However, I'm not sure if there's anything that Carbon can do to fix the issue?

> Is this issue related to a specific component?

`ComboBox` & `DropdownV2`

It should also happen with any component using `ListBox` & `ListBoxField`.

> What browser are you working in?

`Chrome` latest.

> What version of the Carbon Design System are you using?

```
"carbon-components": "9.0.2",
"carbon-components-react": "6.4.3",
"carbon-icons": "7.0.6",
```

## Steps to reproduce the issue

- Clone [the repo](https://github.com/Yohanna/carbon-combobox-error) and run `yarn && yarn start-dev`
- Open `localhost:8888` and check the console to notice the errors

![image](https://user-images.githubusercontent.com/6926228/45972248-40d8f880-c009-11e8-9efd-aab264043422.png)

#### To get rid of the errors

- Remove `react-hot-loader` from `package.json`
- Remove `react-hot-loader/babel` from `.babelrc`
- Run `yarn && yarn start-dev`
- The errors are gone from the console

**Comment by joshblack** [comment] 2018-10-03 15:44
Hey @Yohanna! Going to close this as a duplicate of #857 as I think they are the same root cause. Feel free to comment if that's not the case!

**Closed by joshblack** 2018-10-03 15:44 UTC
