### ISSUE TITLE
FileUpload: The previous uploaded file list is not cleared after we click on the upload button again.

### ISSUE THREAD

**Issue by itdove** [IBM/carbon-components-react#1049] opened 2018-07-04 10:41 UTC
## Detailed description

I use the latest version of carbon-components-react 6.7.4 including the fix for #1022 and since I use that version when I click on the upload button again, the previous list of selected files is not cleared.

The same behavior happen if 'multiple' is set.
before that new release or fix (6.7.4)... the list was automatically cleared at each click of the Upload button.

I'm working for ICP Cloud Foundry.

## Steps to reproduce the issue

Scenario:

`            <FileUploader
                labelTitle="Upload"
                labelDescription="only .yml and .yaml"
                buttonLabel="Upload configuration"
                filenameStatus="edit"
                accept={[".yml", ".yaml"]}
                name="file"
                onChange={uploadConfigAndValidate}
            />
`

https://codesandbox.io/s/llwn4yw349
It seems to work fine on codesandbox.io but not sure it use the same version I use or if so what the problem it my code could be.

1) CLick on the upload button and select a file.
2) The file appears in the list and the onChange event is triggered/ (All fine)
3) Click on the upload button again, select a file... the file name get added to the list of selected files instead of replacing the list.

As you can see also on the screenshot, I can not delete item in the list... which is good for my scenario.

<img width="373" alt="screen shot 2018-07-04 at 6 41 08 am" src="https://user-images.githubusercontent.com/28610057/42272797-50f2aeb8-7f55-11e8-989b-dc61549adef9.png">

**Comment by itdove** [comment] 2018-07-04 10:51
hmmm before I was using an old version of react: "carbon-components-react": "^5.51.5", may be it is a change in the behavior of that component since that version?

**Comment by tw15egan** [comment] 2018-07-13 16:41
@itdove, it seems this issue is no longer relevant since you are using `FileUploaderButton` now, and cannot reproduce it in CodeSandbox. I'm going to close this for now, but if we want to revisit this we can reopen 👍

**Closed by tw15egan** 2018-07-13 16:41 UTC

**Comment by itdove** [comment] 2018-07-13 17:56
@tw15egan but we can't use icon with FileUploaderButton either, can we?

**Comment by tw15egan** [comment] 2018-07-13 18:14
We can track that in the other issue, this one was specifically tracking "The previous uploaded file list is not cleared after we click on the upload button again" and was not reproducible
