### ISSUE TITLE
flatpickr window not defined in isomorphic applications

### ISSUE THREAD

**Issue by codejamninja** [IBM/carbon-components-react#1399] opened 2018-10-05 04:35 UTC
I am still getting an error saying window is not defined when using carbon-components-react in isomorphic applications. It's a similar issue to #868.

```sh
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  1767 | 	position: "auto",
  1768 |
> 1769 | 	animate: window.navigator.userAgent.indexOf("MSIE") === -1,
       | ^
  1770 |
  1771 | 	/* if true, dates will be parsed, formatted, and displayed in UTC.
  1772 |  preloading date strings w/ timezones is recommended but not necessary */


  WebpackError: window is not defined

  - flatpickr.js:1769 Object.<anonymous>
    ~/flatpickr/dist/flatpickr.js:1769:1

  - DatePicker.js:14 Object.assign.i
    ~/carbon-components-react/lib/components/DatePicker/DatePicke    r.js:14:1

  - index.js:27 Object.defineProperty.value
    ~/carbon-components-react/lib/components/DatePicker/index.js:    27:1

  - index.js:797 Object.defineProperty.value
    ~/carbon-components-react/lib/index.js:797:1

  - button.js:2 Object.defineProperty.value
    src/components/button.js:2:1


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-default@1.0.0 build: `gatsby build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-starter-default@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/codejamninja/.npm/_logs/2018-10-05T04_29_19_533Z-debug.log
```

**Comment by asudoh** [comment] 2018-10-05 05:17
@codejamninja Thank you for reporting (again)! Would you want to do another try fixing Flatpickr? Thanks!

**Comment by codejamninja** [comment] 2018-10-05 05:31
I created a pull request to fix this.

https://github.com/IBM/carbon-components/pull/1174

**Comment by tw15egan** [comment] 2018-10-08 19:56
Seems like this is the cause: 

cc @asudoh:
>Thanks @codejamninja for creating a quick PR. Unfortunately the vanilla version depends on older Flatpickr to workaround the DOM structure difference between our design and what Flatpickr expects. Given I think you are not using our vanilla JS version, you can force installing newer version of Flatpicker in your application's package.json. Thanks!

Will need to update flatpickr on user end to alleviate this issue. Going to close this, but feel free to suggest an alternative

**Closed by tw15egan** 2018-10-08 19:56 UTC
