### ISSUE TITLE
Set minimum React version requirement for v10

### ISSUE THREAD

**Issue by asudoh** [IBM/carbon-components-react#1895] opened 2019-02-19 05:03 UTC
Refs #1836.

### Summary

This is is for tracking an effort of setting minimum React version requirement for v10.

### Justification

Recent React releases contain some intriguing features, like Hooks. If we can set a minimum React version requirement for v10, we can introduce new features that depend on such React new features afterwards.

### Desired UX and success metrics

* Setting a minimum React version requirement
* Provide an easy way for users to know above version requirement

### "Must have" functionality

Either (or both) of:

* Documentation
* React version detection and warning code

### Specific timeline issues / requests

Before we ship `v10`.

**Comment by joshblack** [comment] 2019-02-20 23:26
I vote that we set it to `^16.8.2`, but after our update last year it might be worth verifying enzyme support. Was checking out their issue tracker here: https://github.com/airbnb/enzyme/issues/1553 and it seems like hooks may not be supported yet, which could cause some issues for adopters.

I bet we can plan for `16.8.2` for X, but without the enzyme support it might be a hard sell to update until that happens given how many codebases are using it right now.

**Comment by tomkdgun** [comment] 2019-02-26 06:11
Please keep in mind, that is very difficult for many big projects to move to latest version of React quickly. Upgrade of React requires in many cases 3rd party dependencies upgrade, which are also delayed. Last time, to meet Carbon v9 requirement (React 16.4), we spent almost two weeks to modify our code and upgrade over 50+ core 3rd party modules, including webpack and babel. This doesn't include the time spent on legal scans and testing.

**Comment by asudoh** [comment] 2019-02-26 07:01
Thank you @tomkdgun for your feedback! Yes I can imagine that sort of difficulty happens (I used to be in the consumer side before joining Carbon team back in January 2018). We'll carefully monitor the feedback like yours for this kind of effort.

**Comment by IOIO72** [comment] 2019-02-27 12:30
I think it is worth to upgrade React for v10. If there are issues with dependences (like enzyme, etc.) it is worth to delay the release of v10. I guess it's predictible that many developers are motivated to move their products to React Hooks.
Developers who intentionally don't want to upgrade React, should use v9. I ask myself if v9 should be maintained concerning components even after the release of v10 for those developers.

**Comment by asfordmatt** [comment] 2019-02-27 13:09
We're on 16.8.3 already, so not an issue for us :)
I think setting the minimum requirement in a major release like v10 is reasonable, giving teams the option to stay on v9 until they can move up.
BTW I've used hooks in production and could test in Enzyme but with no API to access hooks directly I could only test the effects of the hooks indirectly for now.

**Comment by JSoet** [comment] 2019-02-27 14:50
I would be very hesitant to introduce a requirement like this if the only benefit is so "we can introduce new features that depend on such React new features afterwards"... I think that it would make a lot more sense to wait until there are some actual features which you are considering implementing using hooks and then see if it's possible to implement them as opt in features for users who are using 16.8 or above, and not require everyone to upgrade just for some unknown benefit. I think requiring an upgrade to 16.8 will severely hamper adoption, or will impose a very large cost on a lot of teams, as tomkdgun specified above (since Carbon specifically doesn't try and cover all use cases, but only the 'most common use cases' many teams of course have to rely on 3rd party libraries for other functionality which carbon doesn't include). 

I say this as someone who is planning on (hoping to) find some time within the next release of our product to upgrade us to 16.8 as well. But I know that updating package versions for a few other packages we use has already taken a fair amount of effort, and requiring this kind of change right now so early after hooks have been released before many other libraries have upgraded may prevent many people from adopting carbon X.

Also, given that Carbon X seems to already be quite a big change in terms of design I'm wondering if it makes the most sense to also include this change at the same time? On one hand, most teams will already have to do some work to adopt carbon X anyway, but on the other hand it is just another hurdle which will reduce adoption... 

One other thing I'm not sure about is your guys' current support strategy. Currently since we've only had to use carbon 9 since adopting carbon I haven't looked into this, but do you support older releases at all? e.g. if there is a bug found in the dropdown, will that bug fix be released in a carbon 9 release stream as well as the carbon 10 release stream? Or do you only apply bug fixes to the latest release? I couldn't find the info about this anywhere, but if you do support v9 with bug fixes, then that obviously makes a difference to allowing people to continue to use the older versions if they're not able to upgrade.

Finally one last consideration, I'm not sure what other libraries similar to carbon are doing, if they are also requiring upgrades? Would be interesting to see what their plan is for stuff like this...

**Comment by psachs21** [comment] 2019-02-27 15:55
@JSoet based on @asudoh's comment, I believe the intent was to only make the requirement for carbon X and not for this to affect carbon 9. Correct me if I am wrong. Though any major shift like that does introduce the issue that maintaining bug fixes for both 9 and 10 will become more difficult as the code bases diverge.

**Comment by joshblack** [comment] 2019-02-27 16:14
@JSoet definitely understand the pain you and @tomkdgun described above. The period of time for updating dependencies is such a painful process and is so unenjoyable. I do want to take a moment though to talk a bit about why it's different from the v9 upgrade path, and also to talk about the benefits we get if we do this now instead of waiting till v11 around October.

When looking back to v9, the update for the minimum required React version required a breaking change that had substantial ramifications on the ecosystem given that it fundamentally changed internals of React that a good number of tools relied on (in this case, enzyme being the most prevalent). It also seems to be the case that all libraries will push their major changes around the same time of these kinds of releases which increases the number of things to migrate once again.

However, in this v10 launch, we are moving within the same major version and are only moving up minor versions. With this bump, we finally can add the API enhancements needed for a variety of components, particularly our dropdown suite and data table. More specifically, hooks allow us to drop any sort of render prop pattern and instead rely on hooks and context to provide state management both internally and for external consumers to rely on. This comes up specifically in Data Table when folks might want to react to some stateful value (like selectedRows) or want to programmatically set state (like sorting a column) or want to initialize state a certain way (like initial selected rows).

These are things that could potentially be built into the current implementations of these components, but then we would need to re-write it when we bump our React version because of changes in React's model. APIs like `<Suspense>` fundamentally change how we do component design with React, and being able to use these will significantly increase the quality of components alongside their flexibility for things like remote data access.

Hooks are also a nice addition because we can finally allow readable state in a specific tree:

```js
function MyNestedTableComponent() {
  const state = useContext(DataTableContext);
  // Read from state
}
```

Or allow one to programmatically control state by initializing this in:

```js
function MyDataTable() {
  const [state, dispatch] = useDataTable({
    // Optionally pass in initial state object
  });

  return (
    <>
      <DataTable state={state} dispatch={dispatch} />
      <p>Currently selected rows: {state.selectedRows.length}</p>
      <button onClick={() => dispatch('CLEAR_SELECTED_ROWS')}>
        Programmatically clear selected rows
      </button>
    </>
  );
}
```

Another aspect of v10 is that immediate adoption is not necessarily expected. The visual changes are huge, and as a result on the dev side we have tried to mitigate almost all breaking changes outside of the ones we had to make for accessibility or performance reasons. There is most likely more design debt during this process than technical debt, and this will cause adoption to lag because of how much coordination needs to happen between teams on larger products/platforms.

---

With respect to v9, we will keep branches for each of our versions that can be pushed to/hotfixed when needed. Significant development will no longer occur on these branches, but there are still always available for fixes and can be released when needed 👍

**Comment by JSoet** [comment] 2019-02-27 16:29
Hey @psachs21, thanks, yep, I understand that, the part where I was talking about carbon 9 support was actually just a general question, because I actually didn't know what kind of support the carbon team offers for older releases in general right now.... Sounds like from Josh's comment above that they do support the old releases, so that's good, that means that those who need to stay on v9 can at least get some support still...

@joshblack , sounds good to me, I just wanted to write out some concerns, since the original issue description made this sound very adhoc, like there weren't any specific benefits identified yet, so I wanted to offer a counter-view...

**Comment by vpicone** [comment] 2019-02-27 18:28
I just wanted to share some of the more immediate benefits I could see from upgrading.

**Benefits now**
* Remove the ~10 soon-to-be-deprecated lifecycle methods
* The ref/imperative hooks can be used finally eliminate bugs caused by the HoF solution from previous releases
![screen shot 2019-02-27 at 9 14 25 am](https://user-images.githubusercontent.com/4078018/53500540-23083780-3a70-11e9-8a31-c5d761981c7b.png)

**Future benefits**
* Share logic between similar components (such as event logic) by decoupling state logic
* Offer custom utility hooks to increase the flexibility of more complex components
* Reducing bundle size by using functional components
* Performance enhancements from memo/lazy

**Maintanence benefits**
Not pushing off upgrades decreases future upgrade complexity. With Suspense on the horizon, my personal opinion is that it's important for projects to stay as close to the latest stable react version as possible. 

Like @joshblack mentioned, Enzyme could be an issue. Unfortunately, Enzyme has been slow to implement new react features in the past. I've found that using `mount` instead of `shallow` works just fine for testing components that use hooks. That said, I don't see any harm in updating the dependancy given that it's 100% backwards compatible. We can hold off on actually using hooks until Enzyme supports hooks, but having the dependancy upgrade coincide with major Carbon upgrade seems like a good move.

**Comment by vpicone** [comment] 2019-03-01 19:57
It's worth noting that the only issue remaining with Enzyme and hooks pertains to shallow rendering. If folks are using shallow rendering then the carbon components won't be rendered anyway. The only tests at risk of breaking would be internal, which might be a convenient excuse to switch over to react-testing-library 🤣

**Comment by shinytoyrobots** [comment] 2019-03-27 15:44
Does this issue have a resolution, or was it merely an ongoing discussion?

**Comment by joshblack** [comment] 2019-03-27 15:47
@shinytoyrobots we bumped the version in #2089 👍

**Comment by shinytoyrobots** [comment] 2019-03-27 18:49
OK. Moving this into "Review/QA" as it doesn't actually require any more work, so much as it will be closed by release.

**Closed** 2019-03-29 17:38 UTC
Labels: project: components, type: dev :robot:, type: discussion 💬
