### ISSUE TITLE
Multiselect Dropdown Template Issue 

### ISSUE THREAD

**Issue by anupamsomani1** [IBM/carbon-components-react#1227] opened 2018-08-23 17:38 UTC
## Detailed description

When I am rendering ` 'carbon-components-react'; 6.20.0` React [MuliSelect](http://react.carbondesignsystem.com/?knob-Collapsed%20icon%20text%20%28tileExpandedIconText%29=Collapse&knob-Content%20%28children%29=&knob-Label%20text%20%28labelText%29=Checkbox%20label&knob-Label%20text%20%28labelText%20in%20%3CRadioButton%3E%29=Radio%20button%20label&knob-The%20form%20element%20type%20%28inputType%29=&knob-The%20href%20for%20tab%20%28href%20in%20%3CTab%3E%29=%23&knob-Label%20text%20%28labelText%20in%20%3CDatePickerInput%3E%29=Date%20Picker%20label&knob-Text%20for%20%22show%20less%22%20button%20%28showLessText%29=Show%20less&knob-Label%20in%20the%201st%20item%20%28labelTwo%29=Estimate%20Monthly%20Cost&knob-Step%20of%20up%2Fdown%20arrow%20%28step%29=10&knob-Button%20kind%20%28kind%29=primary&knob-Placeholder%20text%20%28placeHolderText%29=Search&knob-Maximum%20length%20%28maxLength%20in%20%3CTimePicker%3E%29=5&knob-Close%20icon%20description%20%28iconDescription%29=Close%20the%20modal&knob-The%20link%20href%20%28href%20in%20%3CSwitch%3E%29=&knob-The%20SVG%20%60height%60%20attribute%20%28height%29=&knob-The%20SVG%20%60fill%60%20attribute%20%28fill%29=grey&knob-The%20step%20%28step%29=1&knob-The%20number%20of%20lines%20in%20a%20paragraph%20%28lineCount%29=3&knob-Form%20item%20name%20%28name%29=test&knob-The%20SVG%20%60fillRule%60%20attribute%20%28fillRule%29=&knob-ARIA%20label%20of%20the%20copy%20button%20%28copyLabel%29=Copy%20Code&knob-The%20modal%20heading%20%28modalHeading%29=Modal&knob-Form%20validation%20UI%20content%20%28invalidText%20in%20%3CDatePickerInput%3E%29=A%20valid%20value%20is%20required&knob-Secondary%20button%20text%20%28secondaryButtonText%20in%20%3CModalFooter%3E%29=&knob-Form%20control%20type%20%28type%29=&knob-No%20label%20%28hideLabel%20in%20%3CTimePickerSelect%3E%29=true&knob-UI%20type%20%28Only%20for%20%60%3CMultiSelect%3E%60%29%20%28type%29=default&knob-Dropdown%20menu%20label%20%28ariaLabel%20in%20%3CDropdown%3E%29=dropdown%20menu%20label&knob-Optional%20title%20%28title%20in%20%3CModalHeader%3E%29=Example&knob-Primary%20button%20text%20%28primaryButtonText%20in%20%3CModalFooter%3E%29=Save&knob-Optional%20Label%20%28label%20in%20%3CModalHeader%3E%29=Optional%20Label&knob-Copy%20icon%20description%20%28copyButtonDescription%29=&knob-Tooltip%20content%20%28tooltipText%29=Brief%20description%20of%20the%20dotted%2C%20underlined%20word%20above.&knob-Form%20item%20%28name%20in%20%3CTileGroup%3E%29=tile-group&knob-The%20form%20control%20name%20%28name%20in%20%3CRadioButtonGroup%3E%29=radio-button-group&knob-Maximum%20value%20%28max%29=100&knob-Minimum%20value%20%28min%29=0&knob-Label%20in%20the%201st%20item%20%28labelOne%29=Need%20Help%3F&knob-Feedback%20icon%20description%20%28iconDescription%29=Copy%20to%20clipboard&knob-Tab%20index%20%28tabIndex%20in%20%3CDropdown%3E%29=-1&knob-Plceholder%20text%20%28placeholder%20in%20%3CTimePicker%3E%29=hh%3Amm&knob-The%20label%20text%20for%20the%20close%20button%20%28closeButtonLabelText%29=&knob-Text%20for%20%22show%20more%22%20button%20%28showMoreText%29=Show%20more&knob-The%20icon%20%28icon%29=iconInfoGlyph&knob-The%20content%20in%20%3Ctitle%3E%20in%20SVG%20%28description%29=This%20is%20a%20description%20of%20the%20icon%20and%20what%20it%20does%20in%20context&knob-The%20notification%20kind%20%28kind%29=error&knob-The%20title%20%28title%29=Section%201%20title&knob-Close%20icon%20description%20%28iconDescription%20in%20%3CModalHeader%3E%29=Close&knob-The%20link%20href%20%28href%29=%23&knob-Locale%20%28locale%20in%20%3CDatePickerInput%3E%29=en&knob-Feedback%20text%20%28feedback%29=Feedback%20Enabled%20%F0%9F%91%8D&knob-Form%20requirement%20text%20%28messageText%29=&knob-Link%20%28href%20in%20%3CDropdownItem%3E%29=&knob-Max%20height%20%28tileMaxHeight%29=0&knob-The%20initial%20trigger%20text%20%28defaultText%20in%20%3CDropdown%3E%29=Dropdown%20label&knob-ARIA%20label%20%28modalAriaLabel%29=&knob-The%20description%20of%20the%20trigger%20icon%20for%20narrow%20mode%20%28iconDescription%20in%20%3CTabs%3E%29=show%20menu%20options&knob-Placeholder%20text%20%28placeholder%29=Placeholder%20text.&knob-Tooltip%20content%20%28text%29=This%20is%20some%20Tooltip%20text.&knob-Icon%20%28icon%20in%20%3CSwitch%3E%29=none&knob-Optional%20label%20%28modalLabel%29=Label&knob-Tag%20type%20%28type%29=experimental&knob-The%20duration%20for%20successful%20state%20before%20%60onSuccess%60%20fires%20%28successDelay%29=1500&knob-Placeholder%20text%20%28placeholder%20in%20%3CDatePickerInput%3E%29=mm%2Fdd%2Fyyyy&knob-Selected%20text%20%28selectedText%20in%20%3CDropdown%3E%29=&knob-Text%20in%20%3Clegend%3E%20%28legendText%29=Checkbox%20heading&knob-The%20index%20of%20the%20selected%20tab%20%28selected%20in%20%3CTabs%3E%29=1&knob-ARIA%20role%20%28role%20in%20%3CTab%3E%29=presentation&knob-Tab%20index%20%28tabIndex%20in%20%3CTab%3E%29=0&knob-Modal%20heading%20%28modalHeading%29=Modal%20heading&knob-Tab%20index%20%28tabIndex%29=0&knob-Label%20in%20the%201st%20item%20%28linkTextTwo%29=Cost%20Calculator&knob-The%20href%20of%20trigger%20button%20for%20narrow%20mode%20%28triggerHref%20in%20%3CTabs%3E%29=%23&knob-Href%20for%20clicable%20UI%20%28href%29=%23&knob-The%20modal%20label%20%28optional%29%20%28modalLabel%29=Label&knob-ARIA%20role%20%28role%29=alert&knob-The%20text%20in%20the%20trigger%20button%20%28buttonTriggerText%29=Launch%20Modal&knob-Link%20href%20in%20the%201st%20item%20%28linkHrefOne%29=www.google.com&knob-The%20ARIA%20label%20for%20the%20%3Cinput%3E%20%28ariaLabelInput%29=&knob-Dropdown%20type%20%28type%29=default&knob-Butto%20kind%20%28kind%20in%20%3CSwitch%3E%29=anchor&knob-CSS%20class%20name%20%28className%29=some-class&knob-The%20step%20factor%20for%20Shift%2Barrow%20keys%20%28stepMuliplier%29=4&knob-ARIA%20role%20%28role%20in%20%3CTabs%3E%29=navigation&knob-Trigger%20icon%20description%20%28iconDescription%20in%20%3CDropdown%3E%29=&knob-Collapsed%20icon%20text%20%28tileCollapsedIconText%29=Expand&knob-Secondary%20button%20text%20%28secondaryButtonText%29=Secondary%20Button&knob-Open%20%28open%29=true&knob-Primary%20button%20text%20%28primaryButtonText%29=Primary%20Button&knob-The%20icon%20%28icon%20%28regular%29%2Fname%20%28legacy%29%29=iconAdd&knob-How%20long%20the%20text%20is%20shown%20upon%20clicking%20%28feedbackTimeout%29=3000&knob-Close%20after%20submit%20%28shouldCloseAfterSubmit%29=true&knob-Selected%20value%20%28value%20in%20%3CDropdown%3E%29=&knob-Content%20of%20form%20validation%20UI%20%28invalidText%29=A%20valid%20value%20is%20required&knob-Icon%20%28icon%29=none&knob-Open%20%28open%20in%20%3CComposedModal%3E%29=true&knob-The%20maximum%20value%20%28max%29=100&knob-Trigger%20text%20%28triggerText%29=Tooltip%20label&knob-Rows%20%28rows%29=4&knob-The%20text%20shown%20upon%20clicking%20%28feedback%29=Copied%21&knob-The%20minimum%20value%20%28min%29=0&knob-Value%20of%20the%20selected%20item%20%28valueSelected%20in%20%3CTileGroup%3E%29=&knob-Link%20href%20in%20the%202nd%20item%20%28linkHrefTwo%29=www.google.com&knob-The%20text%20in%20the%20secondary%20button%20%28secondaryButtonText%29=Cancel&knob-Form%20item%20name%20%28name%20in%20%3CRadioTile%3E%29=tiles&knob-Loading%20progress%20description%20%28description%29=Loading%20data...&knob-Link%20text%20in%20the%201st%20item%20%28linkTextOne%29=Contact%20Bluemix%20Sales&knob-Value%20%28value%29=50&knob-Icon%20description%20%28iconDescription%29=describes%20the%20close%20button&knob-Label%20for%20minimum%20value%20%28minLabel%29=&knob-Label%20%28label%29=MultiSelect%20Label&knob-Caption%20%28caption%29=Time%20stamp%20%5B00%3A00%3A00%5D&knob-Label%20text%20%28labelText%20in%20%3CTimePickerSelect%3E%29=Please%20select&knob-Title%20%28title%29=Notification%20title&knob-Form%20validation%20UI%20content%20%28invalidText%20in%20%3CTimePicker%3E%29=A%20valid%20value%20is%20required&knob-ARIA%20label%20%28ariaLabel%29=&knob-Subtitle%20%28subtitle%29=Subtitle%20text%20goes%20here.&knob-Label%20for%20maximum%20value%20%28maxLabel%29=&knob-Columns%20%28columns%29=50&knob-Width%20%28in%20px%20or%20%25%29%20of%20single%20line%20of%20text%20or%20max-width%20of%20paragraph%20lines%20%28width%29=100%25&knob-Form%20validation%20UI%20content%20%28invalidText%20in%20%3CSelect%3E%29=A%20valid%20value%20is%20required&knob-ARIA%20label%20of%20the%20container%20%28ariaLabel%29=&knob-Footer%20text=&knob-Form%20validation%20UI%20content%20%28invalidText%29=Invalid%20Selection&knob-Trigger%20icon%20description%20%28iconDescription%20in%20%3CTimePickerSelect%3E%29=open%20list%20of%20options&knob-The%20text%20in%20the%20primary%20button%20%28primaryButtonText%29=Save&knob-Menu%20direction%20%28Only%20with%20%60floatingMenu%60%29%20%28direction%29=bottom&knob-Regular%20expression%20for%20the%20value%20%28pattern%20in%20%3CTimePicker%3E%29=%281%5B012%5D%7C%5B1-9%5D%29%3A%5B0-5%5D%5B0-9%5D%28%5Cs%29%3F%28%3Fi%29&knob-Tooltip%20direction%20%28direction%29=bottom&knob-Current%20progress%20%28currentIndex%29=3&knob-Wrapper%20CSS%20class%20name%20%28wrapperClassName%29=&knob-The%20date%20format%20%28pattern%20in%20%3CDatePickerInput%3E%29=d%7B1%2C2%7D%2Fd%7B4%7D&knob-Helper%20text%20%28helperText%29=Optional%20helper%20text.&knob-Button%20text%20%28buttonText%29=Create&knob-Label%20text%20%28labelText%20in%20%3CTimePicker%3E%29=Select%20a%20time&knob-Active%20%28active%29=true&knob-The%20SVG%20%60width%60%20attribute%20%28width%29=&knob-Value%20of%20the%20selected%20button%20%28valueSelected%20in%20%3CRadioButtonGroup%3E%29=default-selected&selectedKind=MultiSelect&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) component there is some waring message will comes up.
`checkPropTypes.js?a15c:19 Warning: Failed prop type: Invalid prop `children` of type `ListBoxMenuIcon` supplied to `ListBoxField`, expected each child to be one of:`

## Steps to reproduce the issue

`import { MultiSelect } from 'carbon-components-react';`

```
const items = [
  { id: 'item-1', text: 'Item 1' },
  { id: 'item-2', text: 'Item 2' },
];
const App = () => (
  <div>
    <MultiSelect
      label="MultiSelect Label"
      invalid={false}
      invalidText="Invalid Selection"
      items={items}
      itemToString={item => item.text}
    />
  </div>
);

render(
  <App />,
  document.getElementById('root')
);
```
when I am simple running above code then part of rendering and selecting Items in the list warning message will comes up. 

##  Screenshots or code

<img width="943" alt="screen shot 2018-08-23 at 10 20 03 am" src="https://user-images.githubusercontent.com/35505922/44542020-947dbc80-a6c0-11e8-8ce2-34abaeac1e6f.png">

**Comment by joshblack** [comment] 2018-08-23 17:44
Hi @anupamsomani1! 👋 It'd really be helpful if you could follow our [Issue Template](https://github.com/IBM/carbon-components-react/blob/master/.github/ISSUE_TEMPLATE.md). You should have seen it when you created the issue.

Most likely this is related to usage of Hot Module Replacement in webpack, do you feel like it is similar to: https://github.com/IBM/carbon-components-react/issues/857 ?

**Comment by joshblack** [comment] 2018-08-31 17:09
Going to close this as a duplicate of #857. Let me know if that's not the case and we can re-open!

**Closed by joshblack** 2018-08-31 17:09 UTC
