### ISSUE TITLE
data table sort asc -> descending takes 3 clicks

### ISSUE THREAD

**Issue by lounestor** [IBM/carbon-components-react#1244] opened 2018-08-28 10:36 UTC
## Detailed description

there is always 3 state for sorting in the data table
how ever sort order doesn't seem to be replaced
Result is it takes 3 clicks to sort.

'application-header bx--table-sort-v2'
'application-header bx--table-sort-v2 bx--table-sort-v2--active'
'bx--table-sort-v2--ascending'

You can see the behaviour when you
1. select sortable header
2. sort multiple times on active sort header

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue? general issue

> Is this issue related to a specific component? DataTable

> What did you expect to happen? What happened instead? What would you like to see changed?
sort get swapped per click

> What browser are you working in? chrome

> What version of the Carbon Design System are you using? 6.26.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
transformation advisor

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by joshblack** [comment] 2018-08-28 17:09
Hi @lounestor! 👋 Thanks so much for taking the time to make this issue. Going to mark this as a duplicate of #1122, but feel free to comment if you feel like they are different!

**Closed by joshblack** 2018-08-28 17:09 UTC

**Comment by lounestor** [comment] 2018-08-29 08:34
@joshblack ya thats perfect sorry i missed that other related defect
