### ISSUE TITLE
[Checkbox alignment]: Misaligned when label has multiple lines

### ISSUE THREAD

**Issue by gptt916** [IBM/carbon-components-react#1845] opened 2019-02-08 16:53 UTC
## Detailed description

> Describe in detail the issue you're having.

The checkbox and the label text alignment is aligned by centre, but this doesn't look right when the label has multiple lines.
![image](https://user-images.githubusercontent.com/20601623/52491626-8865b880-2b95-11e9-9c53-c9cd085b2090.png)

> Is this issue related to a specific component?

Checkbox

> What did you expect to happen? What happened instead? What would you like to see changed?

Align checkbox to top of first line of label text.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

No

## Steps to reproduce the issue

https://cloud.ibm.com/docs/home/alldocs?locale=it

https://codesandbox.io/s/n78w67qj4j

## Additional information

- Screenshots or code
- Notes

**Comment by emyarod** [comment] 2019-02-11 17:23
hi @gptt916 thanks for reporting this. I believe this is a duplicate of https://github.com/IBM/carbon-components-react/issues/1773 and this should be addressed in the next major version release of Carbon.

cc @asudoh, should we address this in v9 now that this has appeared a few times as an issue for our users? may need input from designers on this as well

**Comment by asudoh** [comment] 2019-02-11 23:08
@emyarod Thank you for pointing out a duplicate! Given I assume style override will be a viable workaround having a solution in `v10` is fine - Closing this for now given that, but anybody please speak up if it's not the case. Thanks!

**Closed by asudoh** 2019-02-11 23:08 UTC

**Comment by natmasse** [comment] 2019-03-20 14:19
@asudoh We won't be moving to V10 soon so can the fix be back ported to V9? We're part of the IBM cloud console.

**Comment by asudoh** [comment] 2019-03-21 01:59
@emyarod Do you think fix can be done via application's style override...? Thanks!

**Comment by emyarod** [comment] 2019-03-21 02:13
@asudoh yes here is an example of repositioning the labels on the application side based on the sandbox link posted earlier in this thread https://codesandbox.io/s/r0l3omz164

**Comment by gptt916** [comment] 2019-03-26 14:14
@emyarod Thanks for the update, for our page I used `top: 7px` instead due to some other styling, however this apparently breaks the clicked styling: 
![image](https://user-images.githubusercontent.com/20601623/55004047-e288d480-4faf-11e9-8855-282b9722c7c7.png)

**Comment by emyarod** [comment] 2019-03-26 15:10
@gptt916 you can adjust the positioning of the pseudoelements as needed https://codesandbox.io/s/mj198j016y

**Comment by gptt916** [comment] 2019-03-26 17:23
Thank you! We have the temp fix working @emyarod
