### ISSUE TITLE
Datatable- rows are not getting updated while props values get updated

### ISSUE THREAD

**Issue by ajaysikdar** [IBM/carbon-components-react#2045] opened 2019-03-19 10:37 UTC
Found in carbon version
```
   "carbon-components": "9.57.0",
    "carbon-components-react": "6.54.1"
```
This works very well in 
```
   "carbon-components": "8.23.1",
    "carbon-components-react": "5.32.0",
```

Rows get updated with `this.props.instances` then rows pass to further `this.rendernstances(rows)`.
The issue is when `this.props.instances` get updated with new values, rows will still have old values.

```
<DataTable
                **rows={this.props.instances}**
                headers={headers}
                render={({ rows, headers, getHeaderProps }) => (
                    <TableContainer >
                        <Table className="" >
                            <TableHead>
                                <TableRow>
                                    {headers.map(header => {
                                        return (
                                            <TableHeader {...getHeaderProps({ header })}>
                                                {header.header}
                                            </TableHeader>
                                        )
                                    })}
                                </TableRow>
                            </TableHead>
                            <TableBody>
                                **{this.rendernstances(rows)}**
                            </TableBody>
                        </Table>
                    </TableContainer>
                )}
            />

```

**Comment by asudoh** [comment] 2019-04-02 02:02
Hi 👋 your example above contains some of specifics in your application (and thus hard to look into). Do you want to create a reduced case based on https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox? Thanks!

**Comment by vpicone** [comment] 2019-04-02 02:33
@asudoh Ah! You're correct, on initial render `open` is undefined, since it's not included in our default props. `undefined && false === undefined` so the defaultProps kick in. 

React default props don't get applied if the result is null (which was my assumption here).

It looks like our solution might be as simple as adding open: false to the defaultProps so that we don't pass in `undefined` to the `active` prop.

`<FocusTrap active={!!open && focusTrap}>` would also do the trick.

**Comment by asudoh** [comment] 2019-04-02 07:37
Hi @vpicone was your response ^ meant to be for #2131? Thanks!

**Comment by reeteshsingh93** [comment] 2019-04-02 09:12
I have tried creating a sandbox application, However its giving me errors:
https://codesandbox.io/embed/jppq1qknkw

After inspecting the issue in my code: i found that data table  component is not re-rendering after prop changes.  In the above code value of "this.props.instances" gets  updated however the value for rows in datatable component  remains same as the initial value.

**Comment by asudoh** [comment] 2019-04-02 09:57
@reeteshsingh93 From my quick glance at your CodeSandbox:

1. `<TableContainer>`, etc. are not named exports of `carbon-components-react`. They are properties under `DataTable` instead.
2. There is no component named `<TableData>` - Probably you meant `<TableCell>`?

**Comment by reeteshsingh93** [comment] 2019-04-02 10:50
@asudoh Thats an incomplete example as we have used tabledata component in our code.Its giving me eerror there.

**Comment by asudoh** [comment] 2019-04-02 12:18
OK great if you can create more isolated case - Thanks!

**Comment by reeteshsingh93** [comment] 2019-04-02 15:40
@asudoh Even changing tabledata to tablecell is giving me same error:
<img width="928" alt="image" src="https://user-images.githubusercontent.com/46310374/55416027-b828af80-558b-11e9-86a9-1e1e8da43142.png">

**Comment by reeteshsingh93** [comment] 2019-04-02 16:43
@asudoh I have updated the example which has similar functionality however we are using "rowValues" in props in our case so that the react component should update.

**Comment by asudoh** [comment] 2019-04-03 04:53
Hi :wave: thank you for sharing your reduced case! The root cause of the problem you are facing is you muted `rowValues` with `.push()`, which is hostile to React which basically expects immutable data. In the component in question in particular - Given there is no change in `rows` prop (same array reference) as you try to add a row, there is no way for Carbon data table to detect the change. You can instead e.g. do `const newRows = rowValues.concat([newObj])` and assign `newRows` to `<DataTable>`. Hope this helps!

**Comment by reeteshsingh93** [comment] 2019-04-03 05:59
@asudoh In our actual case we have used props instead which is meant to re-render the component if its value changes here:
First time when compnent is loaded all the rows are loaded with the initial data , When we perform any action on table rows add/edit/delete the value for "this.props.parsedAdditionalSecurityCapabilities" in our code gets changed however <datatable> rows value doesn't get updated (this same was working in previous carbon version). Since the rows value never gets updated in new version we can't see the changed value without refreshing the page.
<DataTable
                rows={this.props.parsedAdditionalSecurityCapabilities}
                headers={additionalServiceHeaders}
                render={({ rows, headers, getHeaderProps }) => (
                    <TableContainer className="customSolutionTableContainer" title={this.props.t('manage.additional-securities-table.table-header')}>
                        <Table className="AdditionalServiceTable" >
                            <TableHead>
                                <TableRow>
                                    {headers.map(header => {
                                        let sortClass = "";
                                        if (header.key === "url") {
                                            sortClass = "hideSort"
                                        }
                                        return (
                                            <TableHeader translateWithId={this.props.t} className={sortClass} {...getHeaderProps({ header })}>
                                                {header.header}
                                            </TableHeader>
                                        )
                                    })}
                                </TableRow>
                            </TableHead>
                            <TableBody>
                                {this.renderAdditionalServiceInstances(rows)}
                            </TableBody>
                        </Table>
                    </TableContainer>
                )}
            />

**Comment by reeteshsingh93** [comment] 2019-04-03 06:26
Even mutating with the above suggestion in sandbox is not working:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/46310374/55457450-86edc500-5607-11e9-8188-0b708c8f548e.png">

**Comment by asudoh** [comment] 2019-04-03 06:45
Seems that you still have `rowValues` as a global variable. React doesn't detect a change in global variable. You need to manage it as a component state instead.

**Comment by reeteshsingh93** [comment] 2019-04-03 06:48
@asudoh This is similar issue which we are facing https://github.com/IBM/carbon-components-react/issues/740

**Comment by asudoh** [comment] 2019-04-03 06:52
#740 has closed as resolved already? Have you tried my (latest) suggestion?

**Comment by reeteshsingh93** [comment] 2019-04-03 06:53
Yes i implemented it in state locally and it didn't worked for me either.

  renderAdditionalSecurityCapabilities() {

        this.localizeAdditionalServiceHeaders();
     this.state.rowValues = this.props.parsedAdditionalSecurityCapabilities;
      console.log(  this.state.rowValues);
        return (
            <DataTable
                rows={this.state.rowValues}
                headers={additionalServiceHeaders}
                render={({ rows, headers, getHeaderProps }) => (
                    <TableContainer className="customSolutionTableContainer" title={this.props.t('manage.additional-securities-table.table-header')}>
                        <Table className="AdditionalServiceTable" >
                            <TableHead>
                                <TableRow>
                                    {headers.map(header => {
                                        let sortClass = "";
                                        if (header.key === "url") {
                                            sortClass = "hideSort"
                                        }
                                        return (
                                            <TableHeader translateWithId={this.props.t} className={sortClass} {...getHeaderProps({ header })}>
                                                {header.header}
                                            </TableHeader>
                                        )
                                    })}
                                </TableRow>
                            </TableHead>
                            <TableBody>
                                {this.renderAdditionalServiceInstances(rows)}
                            </TableBody>
                        </Table>
                    </TableContainer>
                )}
            />
        );
    }

**Comment by asudoh** [comment] 2019-04-03 07:00
Above is not the right way to update the state: https://reactjs.org/docs/react-component.html#setstate

**Comment by reeteshsingh93** [comment] 2019-04-16 05:04
We figured out the issue with our component, we can close this.

**Comment by asudoh** [comment] 2019-04-16 05:10
Cool thanks @reeteshsingh93!

**Closed by asudoh** 2019-04-16 05:10 UTC
Labels: status: waiting for author's response
