### ISSUE TITLE
Using Modal gives error with react v16.8.0

### ISSUE THREAD

**Issue by embrown30** [IBM/carbon-components-react#2220] opened 2019-04-16 15:27 UTC
## Detailed description

> Describe in detail the issue you're having.

We are including the `Modal` component in our page and get the following error:
![image](https://user-images.githubusercontent.com/5648812/56220767-febfe480-6036-11e9-9ade-8b99dbbd5ec1.png)
![image](https://user-images.githubusercontent.com/5648812/56220831-1ac38600-6037-11e9-92ce-3ebb07fde1f8.png)

> Is this issue related to a specific component?

Modal

> What did you expect to happen? What happened instead? What would you like to see changed?

We expect the Modal component to render

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

6.85.0 version of carbon react
9.69.1 version of carbon components

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

ICP UI

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
> https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by asudoh** [comment] 2019-04-16 21:46
Hi 👋 thank you for reporting - I believe it's a duplicate of #2131, but don't hesitate to let us know if anybody thinks otherwise.

**Closed by asudoh** 2019-04-16 21:46 UTC
Labels: status: needs first aid
