### ISSUE TITLE
AccordionItem title wrpped in P instead of div

### ISSUE THREAD

**Issue by lnesi** [IBM/carbon-components-react#1178] opened 2018-08-10 10:42 UTC
## Detailed description

> Describe in detail the issue you're having.
Accordiong to the documentation at
http://react.carbondesignsystem.com/?selectedKind=Accordion&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

```
<AccordionItem title={<h4 />} onHeadingClick={onHeadingClick()}>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
</p>
</AccordionItem>
```
Can we use div instead of P at:
https://github.com/IBM/carbon-components-react/issues/1178#issue-349466286

Regards

Luis Nesi
luis.nesi@ibm.com

**Comment by asudoh** [comment] 2018-08-10 12:33
Hi 👋 thank you for reporting! Wondering where this request come from, but do you want to do `.your-class .bx--accordion__title { [style for your app] }` meanwhile?

**Comment by kevinkbender** [comment] 2018-08-10 17:03
I would be interested in this as well.

I am trying to put a component that contains a `<div>` in to the AccordionItem's title, but this shows a React warning `Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.`

(It does seem to work fine though, despite the warning.)

**Comment by lnesi** [comment] 2018-08-17 10:27
@asudoh  That work around does not work entirely because we are trying to add a tooltip inside that <p> tag which requires to have actually a div inside a p so that whay maybe we should consider more flexibility.

**Comment by asudoh** [comment] 2018-08-20 02:55
@lnesi Do you have a screenshot wrt what you want to achieve (tooltip inside accordion item header?), along with why your code depends on a particular element type of containing element (is it the same as what @kevinkbender is hitting)? Thanks!

**Comment by psotaond** [comment] 2018-08-23 12:54
I am a IBM Watson Assistant developer and I would also appreciate if I could use different carbon components in the title. A carbon dropdown for example: 

 ![image](https://user-images.githubusercontent.com/5022874/44526415-4084cf00-a6e4-11e8-9313-a8f8820a7559.png)

**Comment by lnesi** [comment] 2018-08-23 16:36
HI @asudoh  we want to have an accordion title with a help icon with a tooltip on it. which requires div to be render inside a p because of how the tooltip component works.

**Comment by joshblack** [comment] 2018-08-23 17:17
Just for context, if we switch to `div` we'll need to add these styles to the `bx--accordion__title` class upstream (derived from `p`)

```css
font-size: 1rem;
line-height: 1.5;
font-weight: 400;
```

**Comment by asudoh** [comment] 2018-08-23 23:13
@IBM/carbon-designers Do those requirements from @psotaond and @lnesi make sense…? Thanks!

**Comment by aagonzales** [comment] 2018-08-24 14:49
Can we see the broader context of where this patterns are being used? I think I'm ok with the tooltip one, but I still don't understand the pattern where you'll need to replace the accordion label with a dropdown.

**Comment by asudoh** [comment] 2018-08-24 23:57
Good point @aagonzales! @psotaond - Taking another look at your screenshot, I started guessing that you simply wanted the dropdown and the accordion expando side-by-side, instead of making the dropdown as part of the accordion title. Moreover, given Carbon has accordion expando at the left, probably you wanted to use our `<Accordion>` code just to achieve the general expand/collapse UI?

**Comment by kevinkbender** [comment] 2018-08-27 14:41
I just wanted to restate some concerns here, since I had started a separate issue that was closed as a duplicate of this.  I think changing the title `<p>` to a `<div>` would not be enough to make the cases in this thread work.

In FireFox (and maybe other browsers), mouse events don't get fired on the children of a `<button>`.  For example, clicking a `<button>`'s inner element causes the `click` event to fire ONLY on the `<button>`.

You can see this behaviour here (try Chrome vs FireFox): https://codesandbox.io/s/2zz03y09lj

This means you can't really put anything that requires mouse events in the title of the accordion, since the accordion title is a `<button>`.
See https://codesandbox.io/s/6j2njyj7pz - the `onSpanClick` function gets called in Chrome, but it doesn't get called in FireFox.

I think this would also affect @lnesi with the tooltip in the title: https://codesandbox.io/s/6yyq0zxq1z

**Comment by psachs21** [comment] 2018-08-28 15:52
Our team could also use these changes. Most concerning is the compatibility with firefox. An option to provide the element via a prop `headerElement` which defaults to `button` would be sufficient. The additional CSS is unfortunate but this issue with firefox doesn't give us much of a choice.

**Comment by asudoh** [comment] 2018-08-29 03:38
Given `<button>` vs. `<div>` topic is merged to here somehow - @kevinkbender @psachs21 What would you expect when user clicks on `<span id="my-test-area-in-accordion-title”>` if the accordion markup were written like below? Should expand/collapse happen? Or not?

```html
<div
  className="bx--accordion__heading">
  <svg class="bx--accordion__arrow" width="7" height="12" viewBox="0 0 7 12">
    <path fill-rule="nonzero" d="M5.569 5.994L0 .726.687 0l6.336 5.994-6.335 6.002L0 11.27z" />
  </svg>
  <div className="bx--accordion__title">
    <input id="bx--checkbox-new" class="bx--checkbox" type="checkbox" value="new" name="checkbox" checked>
    <label for="bx--checkbox-new" class="bx--checkbox-label">Checkbox</label>
    <span id="my-test-area-in-accordion-title">Foo</span>
  </div>
</div>
```

Trying to see if your case is similar to (or same as) @psotaond’s - Which is, using accordion for general-purpose expand/collapse UI. Thanks!

**Comment by psachs21** [comment] 2018-08-29 04:06
I would expect the click event to bubble up to the bx--accordion__title
element and it would expand or collapse. Unless, the onclick handler in
my-test-area-in-accordion-title calls event.stopPropogation() in which case
the click event is not bubbled. But this allows the consumer to make the
choice.

**Comment by psotaond** [comment] 2018-09-03 12:28
@asudoh yes you are right, we already have working version that was made without using the Carbon components. Now we are porting the app to React that is based on Carbon components. See below how the collapsed panels look like:

![image](https://user-images.githubusercontent.com/5022874/44986832-52d4f780-af85-11e8-9c7c-81294bfe4713.png)

User can see/change the type of a response, he can also move up, down /delete each response

**Comment by asudoh** [comment] 2018-09-03 20:36
@IBM/carbon-designers What would our team see the user interface pattern of above screenshot (general-purpose expandable area with arbitrary content in the “title” area)?

1. Carbon should support the pattern
2. Let consumers implement it user-land
3. Carbon should suggest an alternate UX

Thanks!

**Comment by psotaond** [comment] 2018-09-12 06:59
Hi team, I realized that the entire header content is in a Button element that prevents me from adding interactive content as a descendant (Buttons, Links, Dropdowns,..). Could it be replaced by a clickable div for example?

**Closed** 2018-10-01 22:45 UTC
Labels: type: discussion 💬, type: enhancement 💡
